# golangci-lint configuration for Arbor
# Run: golangci-lint run ./...
# Install: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - unconvert
    - whitespace

  settings:
    errcheck:
      check-type-assertions: false  # Allow unchecked type assertions
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too strict for this codebase
        - shadow          # Too many false positives in test files and short-lived err vars

  exclusions:
    rules:
      # Test files can have longer functions and more complexity
      - path: _test\.go
        linters:
          - errcheck

      # Allow fmt.Println in main
      - path: cmd/arbor/main\.go
        linters:
          - forbidigo

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: false

    goimports:
      local-prefixes:
        - github.com/michaeldyrynda/arbor

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
