# golangci-lint configuration for Arbor
# Run: golangci-lint run ./...
# Install: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional recommended linters
    - gofmt
    - goimports
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: false  # Allow unchecked type assertions
    check-blank: false
    
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for this codebase
      - shadow          # Too many false positives in test files and short-lived err vars
      
  goimports:
    local-prefixes: github.com/michaeldyrynda/arbor

issues:
  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - errcheck
        
    # Allow fmt.Println in main
    - path: cmd/arbor/main\.go
      linters:
        - forbidigo
        
  max-issues-per-linter: 50
  max-same-issues: 10
